swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - description: Operations on Jamf Pro accounts
    name: accounts
  - description: Operations on activationcode
    name: activationcode
  - description: Operations on advanced computer searches
    name: advancedcomputersearches
  - description: Operations on advanced mobile device searches
    name: advancedmobiledevicesearches
  - description: Operations on advanced user searches
    name: advancedusersearches
  - description: Operations on allowed file extensions
    name: allowedfileextensions
  - description: Operations on buildings
    name: buildings
  - description: Operations on byoprofiles
    name: byoprofiles
  - description: Operations on categories
    name: categories
  - description: Operations on classes
    name: classes
  - description: Operations on commandflush
    name: commandflush
  - description: Operations on computer applications
    name: computerapplications
  - description: Operations on computerapplicationusage
    name: computerapplicationusage
  - description: Operations on computercheckin
    name: computercheckin
  - description: Operations on computercommands
    name: computercommands
  - description: Operations on computerconfigurations
    name: computerconfigurations
  - description: Operations on computerextensionattributes
    name: computerextensionattributes
  - description: Operations on computergroups
    name: computergroups
  - description: Operations on computerhardwaresoftwarereports
    name: computerhardwaresoftwarereports
  - description: Operations on computerhistory
    name: computerhistory
  - description: Operations on computerinventorycollection
    name: computerinventorycollection
  - description: Operations on computerinvitations
    name: computerinvitations
  - description: Operations on computermanagement
    name: computermanagement
  - description: Operations on computerreports
    name: computerreports
  - description: Operations on computers
    name: computers
  - description: Operations on departments
    name: departments
  - description: Operations on directory bindings
    name: directorybindings
  - description: Operations on disk encryption configurations
    name: diskencryptionconfigurations
  - description: Operations on distributionpoints
    name: distributionpoints
  - description: Operations on dockitems
    name: dockitems
  - description: Operations on ebooks
    name: ebooks
  - description: Operations on fileuploads
    name: fileuploads
  - description: Operations on gsxconnection
    name: gsxconnection
  - description: Operations on Healthcare Listener
    name: healthcarelistener
  - description: Operations on Healthcare Listener rules
    name: healthcarelistenerrule
  - description: Operations on iBeacon regions
    name: ibeacons
  - description: Operations on infrastructure manager
    name: infrastructuremanager
  - description: Operations on JSON Web Tokens
    name: jsonwebtokenconfigurations
  - description: Operations on accounts (Deprecated)
    name: jssuser
  - description: Operations on ldapservers
    name: ldapservers
  - description: Operations on licensedsoftware
    name: licensedsoftware
  - description: Operations on logflush
    name: logflush
  - description: Operations on macapplications
    name: macapplications
  - description: Operations on managedpreferenceprofiles
    name: managedpreferenceprofiles
  - description: Operations on mobiledeviceapplications
    name: mobiledeviceapplications
  - description: Operations on mobiledevicecommands
    name: mobiledevicecommands
  - description: Operations on mobiledeviceconfigurationprofiles
    name: mobiledeviceconfigurationprofiles
  - description: Operations on mobiledeviceenrollmentprofiles
    name: mobiledeviceenrollmentprofiles
  - description: Operations on mobiledeviceextensionattributes
    name: mobiledeviceextensionattributes
  - description: Operations on mobiledevicegroups
    name: mobiledevicegroups
  - description: Operations on mobiledevicehistory
    name: mobiledevicehistory
  - description: Operations on mobiledeviceinvitations
    name: mobiledeviceinvitations
  - description: Operations on mobiledeviceprovisioningprofiles
    name: mobiledeviceprovisioningprofiles
  - description: Operations on mobiledevices
    name: mobiledevices
  - description: Operations on netbootservers
    name: netbootservers
  - description: Operations on networksegments
    name: networksegments
  - description: Operations on osxconfigurationprofiles
    name: osxconfigurationprofiles
  - description: Operations on packages
    name: packages
  - description: Operations on available patch titles from a source
    name: patchavailabletitles
  - description: Operations on patches
    name: patches
  - description: Operations on patch external sources
    name: patchexternalsources
  - description: Operations on patch internal sources
    name: patchinternalsources
  - description: Operations on patch policies
    name: patchpolicies
  - description: Operations on patch reports
    name: patchreports
  - description: Operations on patch software titles
    name: patchsoftwaretitles
  - description: Operations on peripherals
    name: peripherals
  - description: Operations on peripheraltypes
    name: peripheraltypes
  - description: Operations on policies
    name: policies
  - description: Operations on printers
    name: printers
  - description: Operations on removablemmacaddresses
    name: removablemacaddresses
  - description: Operations on restrictedsoftware
    name: restrictedsoftware
  - description: Operations on savedsearches (deprecated)
    name: savedsearches
  - description: Operations on scripts
    name: scripts
  - description: Operations on sites
    name: sites
  - description: Operations on smtpserver
    name: smtpserver
  - description: Operations on softwareupdateservers
    name: softwareupdateservers
  - description: Operations on userextensionattributes
    name: userextensionattributes
  - description: Operations on usergroups
    name: usergroups
  - description: Operations on users
    name: users
  - description: Operations on vppaccounts
    name: vppaccounts
  - description: Operations on vppassignments
    name: vppassignments
  - description: Operations on vppinvitations
    name: vppinvitations
  - description: Operations on webhooks
    name: webhooks
