swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Example Title
  name: API Support
  url: javascript:alert('xss')
  description: "(asd)[javascript:alert``)"
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
